name: Convert to markdown to PDF
on: 
push:
  branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:[16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Japanese font
        run: sudo apt install fonts-ipafont fonts-ipaexfont

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Convert markdwon to pdf
        run: npx md-to-pdf ./*.md

      - name: Commit output pdf files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update output pdf files
